### ISSUE TITLE
Any chance for a version that supports 10.14?

### ISSUE THREAD

**Issue by eisnerguy1** [cyco/power-pete-cheater#1]
I first wanted to say thanks for this. I still need to be on 10.14.6 for some 32-Bit programs so, as of now, I can't use this program. 
<img width="420" alt="Screen Shot 2021-04-17 at 11 37 33 PM" src="https://user-images.githubusercontent.com/3295271/115133422-18a1b280-9fd6-11eb-93b7-db506b04ef0d.png">

 Is there any chance of adding support for 10.14?

Thanks!

**Comment by cyco** [comment]
I added a new release with support for macOS 10.14, could you try it out and let me know if it works?

**Comment by eisnerguy1** [comment]
Thanks!  It works perfectly so far.
